<?php
define('SITE_URL',"https://ccrss.org/database/");
define('MP3_LOCATION',"PARI");
define('MP3_URL',"https://ccrss.org/sound/MP3/");
define('OGG_URL',"https://ccrss.org/sound/OGG/");
define('AIFF_URL',"https://ccrss.org/sound/AIFF/");
define('PICT_URL',"https://s3-us-west-2.amazonaws.com/mpthreebackupfolder/pictures/");
define('PICT_URL2',"https://ccrss.org/database/files/pictures/");
define('PICT_PATH2',"files/pictures/");
session_start();
?>